/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2017-03-07-9e765f2"
#endif /* AVUTIL_FFVERSION_H */
