/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2017-04-05-fb7a819"
#endif /* AVUTIL_FFVERSION_H */
